const quiz = {
  id: "week-25-c2pa",
  title: "DigiCert Weekly Product Quiz #25",
  intro:
    "This week's focus: C2PA, Content Credentials, and how the industry is trying to prove what's real online",
  maxTime: 100,
  questions: [
    {
      question:
        "Which statement best captures what C2PA adds to digital media?",
      options: [
        "A required industry watermark that permanently labels any media that has been altered",
        "A rights-management system that identifies when a media artifact is a copy of an original",
        "A cryptographically verifiable way to attach provenance information about how a piece of media was created or edited",
        "A forensic detection engine that determines whether a media artifact has been altered with AI",
      ],
      correctAnswer: 2,
    },
    {
      question:
        "What does a valid C2PA Content Credential actually tell you?",
      options: [
        "The signed provenance information is intact and can be validated against the asset",
        "The media is authentic in the sense that it reflects real-world truth",
        "The creator owns the copyright to every ingredient used in the asset",
        "The file has not been edited since it was first captured",
      ],
      correctAnswer: 0,
    },
    {
      question:
        "C2PA was founded in 2021 by a coalition of companies and media organizations. Which group best reflects its actual founding members?",
      options: [
        "Google, Canon, Sony, Qualcomm, and Reuters",
        "Google, IBM, The New York Times, and The Associated Press",
        "Adobe, Microsoft, The New York Times, and BBC",
        "Adobe, Microsoft, BBC, Intel, and Arm",
      ],
      correctAnswer: 3,
    },
    {
      question: "In C2PA, what is an \"ingredient\"?",
      options: [
        "A metadata field describing the asset's output format and resolution",
        "A source asset that was used to create or compose the current asset, often carrying its own provenance",
        "A cryptographic hash of the final rendered asset used during validation",
        "A training-data attribution tag generated by the AI model that edited the asset",
      ],
      correctAnswer: 1,
    },
    {
      question:
        "DigiCert's Content Trust beta uses two products to cover C2PA Content Credentials. Which statement best describes how they split the work?",
      options: [
        "Document Trust Manager issues certificates that cameras use to sign authenticity at capture, while Device Trust Manager signs media at scale for publishers and media companies",
        "Document Trust Manager validates C2PA manifests coming from cameras and contributors, while Device Trust Manager signs outbound media from devices on behalf of the publisher",
        "Document Trust Manager signs media at scale for publishers and media companies, while Device Trust Manager lets camera manufacturers embed signed authenticity into images and video at capture",
        "Document Trust Manager signs still images and PDFs for editorial teams, while Device Trust Manager signs video and audio streams from broadcast cameras",
      ],
      correctAnswer: 2,
    },
  ],
};

export default quiz;
